[package]
name = "alds"
version = "0.1.0"
authors = ["Shoya Taguchi <shoyataguchi0@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
